### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by psychonetic** [snipsco/snips-skill-hue#1]
Hello,

I am trying to get this skill running for several hours.
I installed it via the snipsmanager and started.
While starting, I get the following error:
`Error loading skill snipshue: __init__() got an unexpected keyword argument 'locale'`

And I was also wondering, why you have in the travis.yaml file python3 as testing environment. Snipsmanager only works in python2.7. If I try to run snipsmanager with python3 I get another error when I try to install this skill:
`NameError: name 'reload' is not defined`
(because python 3 needs an import for reload).

So how to fix this or can you tell me whats wrong?
